export const GET_ALL_INTERVENCOES_APIARIO = 'GET_ALL_INTERVENCOES_APIARIO';
// export const SAVE_INTERVENCAO_APIARIO = 'SAVE_INTERVENCAO_APIARIO';
export const LOADING_INTERVENCAO_APIARIO = "LOADING_INTERVENCAO_APIARIO";
export const REQUEST_INTERVENCAO_ERROR = "REQUEST_INTERVENCAO_ERROR";
export const DELETE_INTERVENCAO_APIARIO = "DELETE_INTERVENCAO_APIARIO";
