export const GET_ALL_VISITAS_COLMEIA = 'GET_ALL_VISITAS_COLMEIA';
export const SAVE_INTERVENCAO_COLMEIA = 'SAVE_INTERVENCAO_COLMEIA';
export const LOADING_VISITA_COLMEIA = "LOADING_VISITA_COLMEIA";
export const REQUEST_VISITA_ERROR = "REQUEST_VISITA_ERROR";
export const DELETE_VISITA_COLMEIA = "DELETE_VISITA_APIARIO";
