export const GET_ALL_VISITAS_COLMEIA = 'GET_ALL_VISITAS_COLMEIA';
export const SAVE_INTERVENCAO_APIARIO = 'SAVE_INTERVENCAO_APIARIO';
export const LOADING_VISITA_APIARIO = "LOADING_VISITA_APIARIO";
export const REQUEST_VISITA_ERROR = "REQUEST_VISITA_ERROR";
export const DELETE_VISITA_APIARIO = "DELETE_VISITA_APIARIO";
