export const GET_ALL_APICULTORES = 'GET_ALL_APICULTORES';
export const SAVE_APICULTOR = 'SAVE_APICULTOR';
export const LOADING_APICULTOR = 'LOADING_APICULTOR';
export const DELETE_APICULTOR = "DELETE_APICULTOR";
// export const LOGOUT = 'LOGOUT';