export const GET_ALL_APIARIOS = 'GET_ALL_APIARIOS';
export const LOADING_APIARIO = 'LOADING_APIARIO';
export const SAVE_APIARIO = 'SAVE_APIARIO';
export const UPDATE_APIARIO = 'UPDATE_APIARIO';
export const SAVE_APIARIO_ERROR = 'SAVE_APIARIO_ERROR';
export const GET_CIDADES_UF = 'GET_CIDADES_UF';
export const DETALHES_APIARIO = 'DETALHES_APIARIO';
export const DELETE_APIARIO = 'DELETE_APIARIO';