export const GET_ALL_COLMEIAS_BY_COLMEIA = 'GET_ALL_COLMEIAS_BY_COLMEIA';
// export const SAVE_INTERVENCAO_COLMEIA = 'SAVE_INTERVENCAO_COLMEIA';
export const LOADING_INTERVENCAO_BY_COLMEIA = "LOADING_INTERVENCAO_COLMEIA";
export const REQUEST_INTERVENCAO_ERROR = "REQUEST_INTERVENCAO_ERROR";
export const DELETE_INTERVENCAO_COLMEIA = "DELETE_INTERVENCAO_COLMEIA";
